export const ACTIONS = {
  STORE_MOVIES: 'STORE_MOVIES',
  STORE_MOVIE: 'STORE_MOVIE',
  CLEAR_STORE_MOVIES: 'CLEAR_STORE_MOVIES',
  FILTER_BY_RELEASE_DATE: 'FILTER_BY_RELEASE_DATE',
  FILTER_BY_RATING: 'FILTER_BY_RATING',
  HANDLE_FETCH_ERRORS: 'HANDLE_FETCH_ERRORS',
  HANDLE_FETCH_LOADING: 'HANDLE_FETCH_LOADING',
};

export const LOADINGS = {
  MOVIES_LOADING: 'moviesLoading',
  MOVIE_LOADING: 'movieLoading',
};

export const ERRORS = {
  MOVIES_ERROR: 'moviesLoading',
  MOVIE_ERROR: 'movieLoading',
};
