export const ACTIONS = {
  STORE_MOVIES: 'STORE_MOVIES',
  STORE_MOVIE: 'STORE_MOVIE',
  CLEAR_STORE_MOVIES: 'CLEAR_STORE_MOVIES',
  FILTER_BY_RELEASE_DATE: 'FILTER_BY_RELEASE_DATE',
  FILTER_BY_RATING: 'FILTER_BY_RATING',
  HANDLE_FETCH_ERRORS: 'HANDLE_FETCH_ERRORS',
  HANDLE_FETCH_LOADING: 'HANDLE_FETCH_LOADING',
  FETCH_MOVIES_DATA_REQUEST: 'FETCH_MOVIES_DATA_REQUEST',
  FETCH_MOVIE_DATA_REQUEST: 'FETCH_MOVIE_DATA_REQUEST',
};

export const FETCH_HANDLERS = {
  MOVIES: 'MOVIES',
  MOVIE: 'MOVIE',
};
